[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Handle password reset with hash fragments
[[redirects]]
  from = "/reset-password"
  to = "/reset-password"
  status = 200
  force = false

# Ensure SPA routing works
[[redirects]]
  from = "/dashboard"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/transactions"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/expenses"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/banks"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/tithing"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/goals"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/reports"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/index.html"
  status = 200